name: drivebuy
description: "A car marketplace app"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  url_launcher: ^6.2.5
  go_router: ^15.1.3
  http: ^1.2.0
  get_it: ^8.0.3
  image_picker: ^1.1.2
  firebase_core: ^3.14.0
  firebase_core_web: ^2.23.0
  firebase_auth: ^5.6.0
  google_generative_ai: ^0.4.3
  flutter_dotenv: ^5.1.0
  http_parser: ^4.0.2
  flutter_image_compress: ^2.3.0
  path_provider: ^2.1.3
  dio: ^5.8.0+1
  stomp_dart_client: ^2.0.0
  flutter_local_notifications: ^17.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - images/
    - .env

