// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaIz65VJ51_whf6DepIujwI6DZndk1W1w',
    appId: '1:350939662309:web:40f79e74490bc36a73510c',
    messagingSenderId: '350939662309',
    projectId: 'drivebuy-sv123',
    authDomain: 'drivebuy-sv123.firebaseapp.com',
    storageBucket: 'drivebuy-sv123.firebasestorage.app',
    measurementId: 'G-YWG6L01667',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhjepAeI-RJ0OY27ZK9LHr0Jyun-4e8vE',
    appId: '1:350939662309:android:50459030ffa5638573510c',
    messagingSenderId: '350939662309',
    projectId: 'drivebuy-sv123',
    storageBucket: 'drivebuy-sv123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGdiybCP2GbQWLypEn4barIex1SbHWWZg',
    appId: '1:350939662309:ios:0ecfe21a3c735e5273510c',
    messagingSenderId: '350939662309',
    projectId: 'drivebuy-sv123',
    storageBucket: 'drivebuy-sv123.firebasestorage.app',
    iosBundleId: 'com.example.drivebuy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGdiybCP2GbQWLypEn4barIex1SbHWWZg',
    appId: '1:350939662309:ios:0ecfe21a3c735e5273510c',
    messagingSenderId: '350939662309',
    projectId: 'drivebuy-sv123',
    storageBucket: 'drivebuy-sv123.firebasestorage.app',
    iosBundleId: 'com.example.drivebuy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaIz65VJ51_whf6DepIujwI6DZndk1W1w',
    appId: '1:350939662309:web:ecd960ed5220f55173510c',
    messagingSenderId: '350939662309',
    projectId: 'drivebuy-sv123',
    authDomain: 'drivebuy-sv123.firebaseapp.com',
    storageBucket: 'drivebuy-sv123.firebasestorage.app',
    measurementId: 'G-TDDXFPK9PB',
  );
}
